- name: Install nginx
  hosts: all
  remote_user: ashokbharathi.s
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
    - name: Install nginx
      apt: 
        name: nginx
        state: present
    - name: restart nginx
      service: 
        name: nginx
        state: restarted
- name: Install kubectl
  hosts: all
  remote_user: ashokbharathi.s
  become: yes
  become_method: sudo
  tasks:
    - name: Install Kubectl
      apt:
        name: kubectl
- name: Run copy-files role
  hosts: all
  remote_user: ashokbharathi.s
  become: yes
  become_method: sudo  
  roles:
    - copy-files
